[theme]

# Primary accent for interactive elements
primaryColor = '#ff0000'

# Background color for the main content area
backgroundColor = '#3a3a3a'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#2F2F2F'

# Color used for almost all text
textColor = '#ffffff'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
